Integracion de la parte de Servicios con Boostrap
XaviGonzalezMur/laSalleDeliveries pull request #7
Opened 2022-05-21 10:28 UTC by Hortensia1528

2022-05-21 11:29 UTC, jcostair approved these changes

2022-05-21 11:52 UTC, XaviGonzalezMur requested changes
Varias cosas:
1. Los ficheros del directorio .vs no deben incluirse en el commit. No son parte de la página web. Añade en la raíz de tu espacio de trabajo, un fichero ".gitignore" con una linea que contenga ".vs/".

2. todos los tags `<img>` deben tener un atributo "alt" definido.

3. Revisa los tags `<p> `que tienen como cierre un `</h3>`.

4. Los atributos "width" de los `<img>` deben tener sólo un número. Ni "px" ni otros valores. Hay "width" duplicados.

fuente: ejecuta un validador de html https://validator.w3.org/nu subiendo el fichero .html.

2022-05-27 16:39 UTC, XaviGonzalezMur submitted a review, later dismissed

2022-05-27 16:41 UTC, jcostair approved these changes

2022-05-27 16:54 UTC, jcostair approved these changes

2022-05-27 16:55 UTC, marckbcn approved these changes

2022-05-27 16:56 UTC, merged